# Dependencies

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import scipy.stats as st
from scipy.stats import linregress

In [2]:
# Load and Read CSVs
JC201510citibiketripdata = "Resources/JC-201510-citibike-tripdata.csv"
JC201701citibiketripdata = "Resources/JC-201701-citibike-tripdata.csv"

# Read the mouse data and the study results
citi_bike2015 = pd.read_csv(JC201510citibiketripdata)
citi_bike2017 = pd.read_csv(JC201701citibiketripdata)

In [3]:
citi_bike2015.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,376,2015-10-01 00:16:26,2015-10-01 00:22:42,3212,Christ Hospital,40.734786,-74.050444,3207,Oakland Ave,40.737604,-74.052478,24470,Subscriber,1960.0,1
1,739,2015-10-01 00:27:12,2015-10-01 00:39:32,3207,Oakland Ave,40.737604,-74.052478,3212,Christ Hospital,40.734786,-74.050444,24481,Subscriber,1960.0,1
2,2714,2015-10-01 00:32:46,2015-10-01 01:18:01,3193,Lincoln Park,40.724605,-74.078406,3193,Lincoln Park,40.724605,-74.078406,24628,Subscriber,1983.0,1
3,275,2015-10-01 00:34:31,2015-10-01 00:39:06,3199,Newport Pkwy,40.728745,-74.032108,3187,Warren St,40.721124,-74.038051,24613,Subscriber,1975.0,1
4,561,2015-10-01 00:40:12,2015-10-01 00:49:33,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,24668,Customer,NaN,0

In [4]:
citi_bike2017.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,148,2017-01-01 00:21:32,2017-01-01 00:24:01,3276,Marin Light Rail,40.714584,-74.042817,3185,City Hall,40.717733,-74.043845,24575,Subscriber,1983.0,1
1,1283,2017-01-01 00:24:35,2017-01-01 00:45:58,3183,Exchange Place,40.716247,-74.033459,3198,Heights Elevator,40.748716,-74.040443,24723,Subscriber,1978.0,1
2,372,2017-01-01 00:38:19,2017-01-01 00:44:31,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,24620,Subscriber,1989.0,1
3,1513,2017-01-01 00:38:37,2017-01-01 01:03:50,3194,McGinley Square,40.725340,-74.067622,3271,Danforth Light Rail,40.692640,-74.088012,24668,Subscriber,1961.0,1
4,639,2017-01-01 01:47:52,2017-01-01 01:58:31,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,26167,Subscriber,1993.0,1

In [5]:
cb = [citi_bike2015, citi_bike2017]

In [6]:
cb_new = pd.concat(cb)

cb_new

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,376,2015-10-01 00:16:26,2015-10-01 00:22:42,3212,Christ Hospital,40.734786,-74.050444,3207,Oakland Ave,40.737604,-74.052478,24470,Subscriber,1960.0,1
1,739,2015-10-01 00:27:12,2015-10-01 00:39:32,3207,Oakland Ave,40.737604,-74.052478,3212,Christ Hospital,40.734786,-74.050444,24481,Subscriber,1960.0,1
2,2714,2015-10-01 00:32:46,2015-10-01 01:18:01,3193,Lincoln Park,40.724605,-74.078406,3193,Lincoln Park,40.724605,-74.078406,24628,Subscriber,1983.0,1
3,275,2015-10-01 00:34:31,2015-10-01 00:39:06,3199,Newport Pkwy,40.728745,-74.032108,3187,Warren St,40.721124,-74.038051,24613,Subscriber,1975.0,1
4,561,2015-10-01 00:40:12,2015-10-01 00:49:33,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,24668,Customer,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12921,329,2017-01-31 23:11:59,2017-01-31 23:17:28,3273,Manila & 1st,40.721651,-74.042884,3278,Monmouth and 6th,40.725685,-74.048790,26240,Subscriber,1980.0,2
12922,151,2017-01-31 23:12:04,2017-01-31 23:14:35,3185,City Hall,40.717733,-74.043845,3276,Marin Light Rail,40.714584,-74.042817,24451,Subscriber,1986.0,1
12923,647,2017-01-31 23:19:26,2017-01-31 23:30:13,3185,City Hall,40.717733,-74.043845,3190,Garfield Ave Station,40.710467,-74.070039,26209,Subscriber,1988.0,1
12924,295,2017-01-31 23:20:54,2017-01-31 23:25:50,3275,Columbus Drive,40.718355,-74.038914,3214,Essex Light Rail,40.712774,-74.036486,26211,Subscriber,1988.0,1
12925,576,2017-01-31 23:48:37,2017-01-31 23:58:14,3201,Dey St,40.737711,-74.066921,3194,McGinley Square,40.725340,-74.067622,26232,Subscriber,1987.0,1

In [7]:
city_bikes = cb_new.sort_values(by='Bike ID', ascending=True)
city_bikes

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
188,313,2015-10-01 09:51:29,2015-10-01 09:56:42,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,17653,Subscriber,1975.0,1
621,350,2015-10-02 09:15:55,2015-10-02 09:21:46,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,17653,Subscriber,1989.0,1
311,202,2015-10-01 15:02:56,2015-10-01 15:06:18,3203,Hamilton Park,40.727596,-74.044247,3211,Newark Ave,40.721525,-74.046305,17653,Subscriber,1982.0,1
530,123,2015-10-02 00:19:00,2015-10-02 00:21:03,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,17653,Subscriber,1976.0,1
478,878,2015-10-01 20:56:23,2015-10-01 21:11:02,3211,Newark Ave,40.721525,-74.046305,3211,Newark Ave,40.721525,-74.046305,17653,Subscriber,1977.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9923,781,2017-01-25 18:47:50,2017-01-25 19:00:51,3202,Newport PATH,40.727224,-74.033759,3225,Baldwin at Montgomery,40.723659,-74.064194,27205,Subscriber,1984.0,1
10114,429,2017-01-26 07:03:12,2017-01-26 07:10:22,3225,Baldwin at Montgomery,40.723659,-74.064194,3195,Sip Ave,40.730743,-74.063784,27205,Subscriber,1986.0,1
9340,319,2017-01-24 17:56:54,2017-01-24 18:02:13,3272,Jersey & 3rd,40.723332,-74.045953,3205,JC Medical Center,40.716540,-74.049638,27205,Subscriber,1989.0,1
7910,327,2017-01-20 12:34:11,2017-01-20 12:39:38,3225,Baldwin at Montgomery,40.723659,-74.064194,3209,Brunswick St,40.724176,-74.050656,27205,Subscriber,1991.0,1
9596,253,2017-01-25 08:37:19,2017-01-25 08:41:33,3205,JC Medical Center,40.716540,-74.049638,3185,City Hall,40.717733,-74.043845,27205,Subscriber,1983.0,1

In [8]:
cb = city_bikes.rename(columns={'Trip Duration':'Trip Duration (Sec)'})
cb

,Trip Duration (Sec),Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
188,313,2015-10-01 09:51:29,2015-10-01 09:56:42,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,17653,Subscriber,1975.0,1
621,350,2015-10-02 09:15:55,2015-10-02 09:21:46,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,17653,Subscriber,1989.0,1
311,202,2015-10-01 15:02:56,2015-10-01 15:06:18,3203,Hamilton Park,40.727596,-74.044247,3211,Newark Ave,40.721525,-74.046305,17653,Subscriber,1982.0,1
530,123,2015-10-02 00:19:00,2015-10-02 00:21:03,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,17653,Subscriber,1976.0,1
478,878,2015-10-01 20:56:23,2015-10-01 21:11:02,3211,Newark Ave,40.721525,-74.046305,3211,Newark Ave,40.721525,-74.046305,17653,Subscriber,1977.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9923,781,2017-01-25 18:47:50,2017-01-25 19:00:51,3202,Newport PATH,40.727224,-74.033759,3225,Baldwin at Montgomery,40.723659,-74.064194,27205,Subscriber,1984.0,1
10114,429,2017-01-26 07:03:12,2017-01-26 07:10:22,3225,Baldwin at Montgomery,40.723659,-74.064194,3195,Sip Ave,40.730743,-74.063784,27205,Subscriber,1986.0,1
9340,319,2017-01-24 17:56:54,2017-01-24 18:02:13,3272,Jersey & 3rd,40.723332,-74.045953,3205,JC Medical Center,40.716540,-74.049638,27205,Subscriber,1989.0,1
7910,327,2017-01-20 12:34:11,2017-01-20 12:39:38,3225,Baldwin at Montgomery,40.723659,-74.064194,3209,Brunswick St,40.724176,-74.050656,27205,Subscriber,1991.0,1
9596,253,2017-01-25 08:37:19,2017-01-25 08:41:33,3205,JC Medical Center,40.716540,-74.049638,3185,City Hall,40.717733,-74.043845,27205,Subscriber,1983.0,1

In [9]:
cb['Bike ID'].unique()

array([17653, 19086, 19558, 22069, 22535, 23242, 23480, 23660, 23668,
       24377, 24378, 24379, 24386, 24387, 24388, 24389, 24390, 24391,
       24392, 24393, 24394, 24395, 24396, 24397, 24398, 24399, 24400,
       24401, 24402, 24403, 24404, 24405, 24406, 24407, 24408, 24409,
       24411, 24412, 24413, 24414, 24415, 24416, 24417, 24418, 24419,
       24420, 24421, 24422, 24424, 24425, 24426, 24427, 24428, 24429,
       24430, 24431, 24432, 24433, 24434, 24435, 24436, 24437, 24438,
       24439, 24440, 24441, 24442, 24443, 24444, 24445, 24446, 24447,
       24448, 24449, 24450, 24451, 24452, 24453, 24454, 24455, 24456,
       24457, 24458, 24459, 24460, 24461, 24462, 24463, 24464, 24465,
       24466, 24467, 24468, 24469, 24470, 24471, 24472, 24473, 24474,
       24476, 24477, 24478, 24479, 24480, 24481, 24482, 24483, 24484,
       24485, 24486, 24487, 24488, 24489, 24490, 24491, 24492, 24493,
       24494, 24495, 24496, 24497, 24498, 24499, 24500, 24501, 24502,
       24503, 24504, 24505, 24506, 24508, 24509, 24510, 24511, 24512,
       24513, 24514, 24515, 24516, 24517, 24519, 24520, 24521, 24522,
       24524, 24525, 24526, 24527, 24528, 24529, 24530, 24531, 24532,
       24533, 24535, 24536, 24537, 24538, 24539, 24540, 24541, 24542,
       24543, 24544, 24546, 24547, 24548, 24549, 24550, 24551, 24552,
       24553, 24554, 24555, 24556, 24557, 24558, 24559, 24560, 24561,
       24562, 24563, 24564, 24565, 24566, 24567, 24568, 24569, 24570,
       24571, 24572, 24573, 24574, 24575, 24576, 24577, 24578, 24579,
       24581, 24582, 24583, 24584, 24585, 24586, 24587, 24588, 24589,
       24590, 24591, 24592, 24593, 24594, 24595, 24596, 24597, 24599,
       24600, 24601, 24602, 24603, 24604, 24605, 24606, 24607, 24608,
       24609, 24610, 24611, 24612, 24613, 24614, 24615, 24616, 24618,
       24619, 24620, 24621, 24622, 24623, 24624, 24625, 24626, 24627,
       24628, 24629, 24630, 24631, 24632, 24633, 24634, 24635, 24636,
       24637, 24638, 24639, 24640, 24641, 24642, 24643, 24644, 24645,
       24646, 24647, 24648, 24649, 24650, 24651, 24652, 24653, 24654,
       24655, 24656, 24658, 24659, 24660, 24661, 24662, 24663, 24664,
       24665, 24666, 24667, 24668, 24669, 24670, 24671, 24672, 24673,
       24674, 24675, 24676, 24677, 24678, 24679, 24680, 24681, 24682,
       24683, 24684, 24685, 24686, 24687, 24688, 24689, 24690, 24691,
       24692, 24693, 24694, 24695, 24696, 24697, 24698, 24699, 24700,
       24701, 24702, 24703, 24704, 24705, 24707, 24709, 24710, 24711,
       24712, 24713, 24714, 24715, 24716, 24717, 24718, 24719, 24720,
       24721, 24722, 24723, 24724, 26151, 26153, 26154, 26155, 26157,
       26161, 26162, 26163, 26164, 26165, 26167, 26168, 26169, 26170,
       26171, 26172, 26173, 26174, 26175, 26177, 26178, 26180, 26181,
       26182, 26183, 26184, 26186, 26187, 26188, 26190, 26191, 26192,
       26193, 26194, 26195, 26197, 26198, 26199, 26200, 26201, 26204,
       26205, 26207, 26208, 26209, 26210, 26211, 26213, 26215, 26216,
       26217, 26219, 26220, 26221, 26223, 26225, 26227, 26228, 26230,
       26231, 26232, 26234, 26235, 26238, 26240, 26241, 26244, 26245,
       26246, 26247, 26248, 26250, 26253, 26254, 26255, 26256, 26258,
       26260, 26262, 26263, 26265, 26266, 26267, 26268, 26269, 26270,
       26271, 26272, 26273, 26276, 26278, 26279, 26281, 26283, 26286,
       26287, 26291, 26292, 26293, 26294, 26296, 26297, 26298, 26300,
       26301, 26302, 26304, 26305, 26306, 26308, 26309, 26312, 26314,
       26317, 26431, 27205])

In [10]:
cb.dtypes

Trip Duration (Sec)          int64
Start Time                  object
Stop Time                   object
Start Station ID             int64
Start Station Name          object
Start Station Latitude     float64
Start Station Longitude    float64
End Station ID               int64
End Station Name            object
End Station Latitude       float64
End Station Longitude      float64
Bike ID                      int64
User Type                   object
Birth Year                 float64
Gender                       int64
dtype: object

In [11]:
cb = cb.fillna(0)
cb

,Trip Duration (Sec),Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
188,313,2015-10-01 09:51:29,2015-10-01 09:56:42,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,17653,Subscriber,1975.0,1
621,350,2015-10-02 09:15:55,2015-10-02 09:21:46,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,17653,Subscriber,1989.0,1
311,202,2015-10-01 15:02:56,2015-10-01 15:06:18,3203,Hamilton Park,40.727596,-74.044247,3211,Newark Ave,40.721525,-74.046305,17653,Subscriber,1982.0,1
530,123,2015-10-02 00:19:00,2015-10-02 00:21:03,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,17653,Subscriber,1976.0,1
478,878,2015-10-01 20:56:23,2015-10-01 21:11:02,3211,Newark Ave,40.721525,-74.046305,3211,Newark Ave,40.721525,-74.046305,17653,Subscriber,1977.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9923,781,2017-01-25 18:47:50,2017-01-25 19:00:51,3202,Newport PATH,40.727224,-74.033759,3225,Baldwin at Montgomery,40.723659,-74.064194,27205,Subscriber,1984.0,1
10114,429,2017-01-26 07:03:12,2017-01-26 07:10:22,3225,Baldwin at Montgomery,40.723659,-74.064194,3195,Sip Ave,40.730743,-74.063784,27205,Subscriber,1986.0,1
9340,319,2017-01-24 17:56:54,2017-01-24 18:02:13,3272,Jersey & 3rd,40.723332,-74.045953,3205,JC Medical Center,40.716540,-74.049638,27205,Subscriber,1989.0,1
7910,327,2017-01-20 12:34:11,2017-01-20 12:39:38,3225,Baldwin at Montgomery,40.723659,-74.064194,3209,Brunswick St,40.724176,-74.050656,27205,Subscriber,1991.0,1
9596,253,2017-01-25 08:37:19,2017-01-25 08:41:33,3205,JC Medical Center,40.716540,-74.049638,3185,City Hall,40.717733,-74.043845,27205,Subscriber,1983.0,1

In [14]:
cb.to_csv("Resources/CitiBikeData.csv", index=False)